# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('inheritGroupSettings', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RancidGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rancidGroup', models.CharField(max_length=100)),
                ('djangoGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RancidGroupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rancidGroup', models.CharField(max_length=100)),
                ('settingName', models.CharField(max_length=20)),
                ('settingValue', models.CharField(max_length=100)),
            ],
        ),
    ]
